name: GitHub Actions Demo
run-name: Demo GitHub Actions 🚀
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is a demo file"
