name: GitHub metrics
on:
  schedule:
    - cron: "0 0 * * *" 
  push:
    branches: "master"
jobs:

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
  
      - name: Personal metrics
        uses: lowlighter/metrics@v3.10
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: "header, activity, community, repositories"
          
          plugin_lines: yes
          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_provider: spotify
          plugin_music_playlist: https://open.spotify.com/playlist/2CIhTmXs8Q9lUIHmoVAL8U?si=25d0ed4957a54806
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_sort: random
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          config_timezone: Asia/Kolkata
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_stargazers: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 100
          plugin_people_size: 28
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0      
          repositories_forks: yes
          plugin_skyline: yes
          plugin_skyline_year: 0
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1
          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 14
          plugin_reactions_details: percentage, count
          plugin_achievements: yes
          plugin_achievements_threshold: C       
          plugin_achievements_secrets: yes   
          plugin_achievements_limit: 0
          plugin_notable: yes
          plugin_notable_filter: stars:>50
          plugin_tweets_attachments: yes
          plugin_support: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_user: .user.login   

          
      - name: Personal metrics (detailed)
        uses: lowlighter/metrics@v3.10
        with:
          filename: metrics.detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: "metadata"
          plugin_gists: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: .user.website
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage 
          plugin_languages_limit: 8 
          plugin_pagespeed_screenshot: yes
          plugin_posts: yes
          plugin_posts_source: dev.to
          config_timezone: Asia/Kolkata
          plugin_languages_colors : "rainbow"
